-- Criação da tabela de membros do projeto para vincular colaboradores a projetos
-- Execute este comando no SQL Editor do seu Supabase Dashboard

CREATE TABLE IF NOT EXISTS project_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_projeto BIGINT NOT NULL,
    id_colaborador BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Chaves estrangeiras com delete cascade
    CONSTRAINT fk_projeto 
        FOREIGN KEY (id_projeto) 
        REFERENCES dim_projetos ("ID_Projeto") 
        ON DELETE CASCADE,
        
    CONSTRAINT fk_colaborador 
        FOREIGN KEY (id_colaborador) 
        REFERENCES dim_colaboradores ("ID_Colaborador") 
        ON DELETE CASCADE,

    -- Evitar duplicatas
    CONSTRAINT project_members_unique UNIQUE (id_projeto, id_colaborador)
);

-- Habilitar RLS (Row Level Security) para segurança
ALTER TABLE project_members ENABLE ROW LEVEL SECURITY;

-- Políticas de acesso (Ajuste conforme suas necessidades de Auth)
-- Permitir leitura para todos os usuários autenticados
CREATE POLICY "Enable read access for all users" ON project_members
    FOR SELECT USING (auth.role() = 'authenticated');

-- Permitir inserção/deleção apenas para admins (se você tiver role no auth.users)
-- Caso contrário, para simplificar e permitir que o sistema funcione agora:
CREATE POLICY "Enable all access for authenticated users" ON project_members
    FOR ALL USING (auth.role() = 'authenticated');
