import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export const editImageWithGemini = async (
  base64Image: string,
  prompt: string
): Promise<string> => {
  try {
    // Extract MimeType and Data from the Data URL
    // Format: data:[<mediatype>][;base64],<data>
    const match = base64Image.match(/^data:([a-zA-Z0-9]+\/[a-zA-Z0-9-.+]+);base64,(.+)$/);
    
    let mimeType = 'image/jpeg'; // Default fallback
    let data = base64Image;

    if (match) {
      mimeType = match[1];
      data = match[2];
    } else {
       // Attempt to handle raw base64 or other formats if necessary
       const split = base64Image.split(',');
       if (split.length === 2) {
           data = split[1];
       }
    }

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: mimeType,
              data: data,
            },
          },
          {
            text: prompt,
          },
        ],
      },
    });

    // Extract the image from the response
    if (response.candidates && response.candidates[0].content.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData && part.inlineData.data) {
          // Gemini returns raw base64, we need to prepend the data header for the browser
          return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }

    throw new Error("No image generated by Gemini.");
  } catch (error) {
    console.error("Error editing image with Gemini:", error);
    throw error;
  }
};

// "types": ["vite/client", "node"]